Lesson 4
Mentavr/if-html pull request #4
Opened 2020-12-02 13:59 UTC by Mentavr

add html-What do we offer, homework 4 + BEM

2020-12-02 16:29 UTC, nikitik-nikita commented on css/style.css
> +    font-weight: 47px;
некорректное значение

2020-12-02 16:29 UTC, nikitik-nikita commented on css/style.css
> +}
стили к `head`?

2020-12-02 16:29 UTC, nikitik-nikita commented on index.html
> +<head class="page">
стили к `head`?

2020-12-02 16:29 UTC, nikitik-nikita commented on index.html
> +                    <h1 class="company__title_text services__company__offer_text_p company__title-chek">What do we offer</h1>
полагаю можно объединить стили для `h1` (упростить)

2020-12-02 22:27 UTC, Mentavr commented on css/style.css
> +}
оу, к html

2020-12-02 22:28 UTC, Mentavr commented on index.html
> +<head class="page">
меня больше интересует правильность названия для БЭМ

2020-12-02 22:29 UTC, Mentavr commented on index.html
> +                    <h1 class="company__title_text services__company__offer_text_p company__title-chek">What do we offer</h1>
ок

2020-12-02 22:39 UTC, Mentavr commented on index.html
> +                    <h1 class="company__title_text services__company__offer_text_p company__title-chek">What do we offer</h1>
просто сделал контейнер для оранжевой полоски, я думал она в будущем нужна для подчеркивания активного заголовка по всей странице

2020-12-03 20:37 UTC, xStanislau requested changes

2020-12-03 20:37 UTC, xStanislau commented on index.html
> +            <div class="services__company__wrapper center">
Блоки нужно называть по принципу отвечая на вопрос "что это?" и порядок классов должен быть такой как и в html тогда будет понятно как вложены элементы друг в друга и проще в голове представлять структуру

1. Давай договоримся как мы отделяем блок и элемент - двумя нижними подчеркиваниями block__element, блок и модификатор блока - или одним нижним  или двумя верхним тире block_modifier или block--modifier,
если выберешь нижним - тогда его использовать нельзя будет, пример:
`.block-name {} // просто название блока из двух частей search-bar`
`.block-name__element {} // просто название блока из двух частей search-bar__input`
`.block_modifier { background: red} //модификатор search-bar_red `

2. У элемента не может быть элемента - элемент может быть только у блока поэтому не может быть конструкций таких как block__elem__elem
Элемент может быть блоком и элементом есть у нас например кнопка (это блок тк может использоваться много где) но эту кнопку мы положили в футер например на странице и надо задать отступ:

```
.btn {
  font-size: 16px;

} //block

.footer {} // block

.footer__btn {
 margin-left: 20px;
} // кнопка одновременно и элемент футера и блок 

 в разметке было бы
 
<footer class="footer">
  <button class="btn footer__btn">Button</button>
</footer>
```
Тут хорошо написано: https://nicothin.pro/idiomatic-pre-CSS/#bem-elem-in

2020-12-04 09:05 UTC, nikitik-nikita reviewed
так же выровняй контент по центру экрана.
удали папку `about` и файл `indexhomwork.html`, чтобы в этой ветке были файлы к нужному дз.

2020-12-21 05:41 UTC, merged